### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HeronCheng**
老師晚安，以下是我的作業連結，再麻煩您
謝謝老師~

http://18.180.51.21:3000/
http://18.180.51.21:3000/attraction/220
http://18.180.51.21:3000/booking

### CODE REVIEW

**Comment by cwpeng** [comment]
Separating lines should be only 1px height.

**Comment by HeronCheng** [comment]
老師早安，我把 border 1px 修正成 0.5px了，再麻煩您幫我看看有沒有其他問題~

http://18.180.51.21:3000/
http://18.180.51.21:3000/attraction/220
http://18.180.51.21:3000/booking

**Comment by cwpeng** [comment]
I see no changes. 0.5px is rounded to 1px in many browsers, try to find another way.

**Comment by HeronCheng** [comment]
老師晚安，我把border 改成border-top了~

http://18.180.51.21:3000/
http://18.180.51.21:3000/attraction/220
http://18.180.51.21:3000/booking

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Pull request merged**
