### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by HeronCheng**
老師好，我是鄭羽筑(discord名字是Heron)，以下是我的作業網址，再麻煩您幫我看看哪裡有問題需要修改~

http://18.180.51.21:3000/api/attractions?page=1
http://18.180.51.21:3000/api/attractions?page=0&keyword=藝術
http://18.180.51.21:3000/api/attraction/100

### CODE REVIEW

**Comment by cwpeng** [comment]
There is unexpected error when I test this URL: http://18.180.51.21:3000/api/attractions?page=0&keyword=%E5%8C%97

Fix it, create new commit, and leave message for me to review again.

**Comment by HeronCheng** [comment]
老師好，我有調整過我的程式碼了，再麻煩您~

**Comment by cwpeng** [comment]
another error: http://18.180.51.21:3000/api/attractions?page=1&keyword=%E5%8C%97

**Comment by HeronCheng** [comment]
老師，謝謝你讓我發現我的程式碼中有些資料型態不同造成的錯誤，我又再做了一次修正，抱歉又要再麻煩您了

**Comment by cwpeng** [comment]
We should assume attraction data may be changing (increase or decrease) during the lifetime of website, so you cannot just use constant number for final page checking, I mean this code: `if page=='4':`.

We should get total number of rows in attractions or filtered attractions by `SELECT count(*) ...` statement, try it to replace your `if page=='4':` logic and
```
cursor.execute("SELECT * FROM `attraction` WHERE `name` LIKE '%"+keyword+"%';")
```

**Comment by HeronCheng** [comment]
老師晚安，感謝老師的提點，這次的修正再麻煩您~

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
